# Generated by Django 5.2.7 on 2025-10-26 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='字段唯一标识', max_length=100, unique=True)),
                ('label', models.CharField(help_text='字段显示名称', max_length=100)),
                ('data_type', models.CharField(default='string', max_length=20)),
                ('enum_values', models.JSONField(blank=True, help_text='枚举值列表', null=True)),
                ('validation_regex', models.CharField(blank=True, help_text='验证正则表达式', max_length=255, null=True)),
                ('required', models.BooleanField(default=False, help_text='是否必填')),
                ('ui_order', models.IntegerField(default=0, help_text='UI显示顺序')),
                ('help_text', models.TextField(blank=True, help_text='字段帮助文本', null=True)),
                ('custom_prompt', models.TextField(blank=True, help_text='自定义Prompt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ui_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_raw', models.TextField(help_text='原始抽取值')),
                ('normalized_value', models.TextField(blank=True, help_text='标准化后的值', null=True)),
                ('confidence', models.FloatField(default=0.0, help_text='置信度')),
                ('page_num', models.IntegerField(help_text='所在页码', null=True)),
                ('bbox', models.JSONField(blank=True, help_text='边界框坐标', null=True)),
                ('model_name', models.CharField(help_text='使用的模型名称', max_length=100)),
                ('model_version', models.CharField(help_text='模型版本', max_length=20)),
                ('prompt_version', models.IntegerField(help_text='Prompt版本')),
                ('verified', models.BooleanField(default=False, help_text='是否已验证')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_results', to='documents.document')),
                ('field_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_results', to='extractions.fielddefinition')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('corrected_value', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extraction_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to='extractions.extractionresult')),
                ('verifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
