# Generated by Django 5.2.7 on 2025-10-26 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='模板名称', max_length=100)),
                ('system_prompt', models.TextField(help_text='系统提示词')),
                ('field_prompts', models.JSONField(help_text='字段提示词映射')),
                ('default_prompt', models.TextField(help_text='默认提示词')),
                ('llm_model', models.CharField(default='gpt-4-turbo', help_text='使用的LLM模型', max_length=100)),
                ('version', models.IntegerField(default=1, help_text='模板版本')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='是否激活')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PromptTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(help_text='测试的字段', max_length=100)),
                ('sample_text', models.TextField(help_text='测试样本文本')),
                ('extracted_value', models.TextField(blank=True, help_text='抽取的值', null=True)),
                ('confidence', models.FloatField(default=0.0, help_text='置信度')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_test_results', to=settings.AUTH_USER_MODEL)),
                ('prompt_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results', to='prompts.prompttemplate')),
            ],
        ),
    ]
