# Generated by Django 5.2.7 on 2025-10-26 13:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', '调试'), ('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('source', models.CharField(blank=True, help_text='日志来源', max_length=100, null=True)),
                ('context', models.JSONField(blank=True, help_text='日志上下文', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level'], name='audit_syste_level_cb3535_idx'), models.Index(fields=['source'], name='audit_syste_source_2c6cd9_idx'), models.Index(fields=['created_at'], name='audit_syste_created_a07dce_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('upload', '上传'), ('extract', '抽取'), ('verify', '验证'), ('test', '测试')], max_length=20)),
                ('entity_type', models.CharField(help_text='操作的实体类型', max_length=100)),
                ('entity_id', models.CharField(blank=True, help_text='操作的实体ID', max_length=255, null=True)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.JSONField(blank=True, help_text='操作详情', null=True)),
                ('prompt_text', models.TextField(blank=True, help_text='使用的Prompt', null=True)),
                ('model_response', models.TextField(blank=True, help_text='模型响应', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx'), models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx')],
            },
        ),
    ]
